on:
  push:
    branches:
    - master
    - feature/*

name: Run tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
          npm install
          npm run build --if-present
          npm test